name: run scraper.py

on:
  schedule:
    - cron: '0 0 * * *' # At midnight every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to GitHub runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          
      - name: Install Playwright browsers for Python
        run: |
          python -m playwright install --with-deps

      - name: verify installed packages
        run: python -m pip list
          
      - name: execute py script # run scraper.py
        run: python scraper.py # No environment variables needed
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
